<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3p8r4iw\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3p8r4iw/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/Container3p8r4iw.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\Container3p8r4iw\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \Container3p8r4iw\Shopware_Core_KernelProdContainer([
    'container.build_hash' => '3p8r4iw',
    'container.build_id' => '874bf16f',
    'container.build_time' => 1775362021,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3p8r4iw');
